---
- hosts: localhost
  vars:
    tenant_id: "xxx"


  tasks:
  - name: Create Group
    azure_rm_adgroup:
      tenant: "{{ tenant_id }}"
      display_name: "Group-Name"
      mail_nickname: "Group-Mail-Nickname"
      state: 'present'
