---
- hosts: localhost
  vars:
    location: "westus"
    rg_name: "mryDynamicResourceGroup"


  tasks:
  - name: Create a resource group
    azure_rm_resourcegroup:
      name: "{{ location }}"
      location: "{{  rg_name }}"
      tags:
          testing: testing
          delete: never
