---
- hosts: localhost
  connection: local
  vars:
    tenant_id: "xxx"


  tasks:
  - name: Create Group
    azure.azcollection.azure_rm_adgroup:
      tenant: "{{ tenant_id }}"
      display_name: "Group-Name"
      mail_nickname: "Group-Mail-Nickname"
      state: 'present'
    register: created_group_info

  - name:  Print created group information
    ansible.builtin.debug:
      var: created_group_info
