---
- hosts: localhost
  connection: local
  vars:
    location: "westus"
    rg_name: "mryDynamicResourceGroup"


  tasks:
  - name: Create a resource group
    azure_rm_resourcegroup:
      name: "{{ rg_name }}"
      location: "{{  location }}"
      tags:
          testing: testing
          delete: never
