---
- hosts: localhost
  connection: local
  vars:
    user_display_name: "xxx"
    tenant_id: "xxx"
    user_id: "user-redhat"
    user_principal_name: "{{ user_id }}"
    #immutable_id: "{{ object_id }}"
    given_name: "First"
    surname: "Last"
    user_type: "Member"
    usage_location: "US"
    mail: "{{ user_id }}@redhat.com"
    password: "th3C0mplexPa55w0rd!"


  tasks:
  - name: Create user
    azure.azcollection.azure_rm_aduser:
      user_principal_name: "{{ user_id }}"
      tenant: "{{ tenant_id }}"
      state: "present"
      account_enabled: "True"
      display_name: "{{ user_display_name }}"
      password_profile: "{{ password }}"
      mail_nickname: "test2"
      #immutable_id: "{{ object_id }}"
      given_name: "{{ given_name }}"
      surname: "{{ surname }}"
      user_type: "{{ user_type }}"
      usage_location: "{{ usage_location }}"
      mail: "{{ mail }}"
    register: create_user_info

  - name: Stashing the group object_id away for later
    ansible.builtin.set_stats:
      data:
        user_object_id: "{{ created_user_info.object_id }}"
        user_default_password: "{{ password }}"
        user_principal: "{{ user_id }}"
      aggregate: no

