---
- hosts: localhost
  connection: local
  vars:
    tenant_id: "xxx"
    group_display_name: "aap-default-group-name"
    group_mail_nickname: "aap-group-mail-nickname"


  tasks:
  - name: Create Group
    azure.azcollection.azure_rm_adgroup:
      tenant: "{{ tenant_id }}"
      display_name: "{{ group_display_name }}"
      mail_nickname: "{{ group_mail_nickname }}"
      state: 'present'
    register: created_group_info


  - name: Stashing the group object_id away for later
    ansible.builtin.set_stats:
      data:
        user_object_id: created_group_info.object_id
      aggregate: no

