---
- hosts: localhost
  connection: local
  vars:
    tenant_id: "xxx"
    user_id: "user-redhat"
    user_principal_name: "{{ user_id }}"
    #immutable_id: "{{ object_id }}"
    given_name: "First"
    surname: "Last"
    user_type: "Member"
    usage_location: "US"
    mail: "{{ user_id }}@redhat.com"


  tasks:
  - name: Create user
    azure.azcollection.azure_rm_aduser:
      user_principal_name: "{{ user_id }}"
      tenant: "{{ tenant_id }}"
      state: "present"
      account_enabled: "True"
      display_name: "Test_{{ user_principal_name }}_Display_Name"
      password_profile: "password"
      mail_nickname: "test2"
      #immutable_id: "{{ object_id }}"
      given_name: "{{ given_name }}"
      surname: "{{ surname }}"
      user_type: "{{ user_type }}"
      usage_location: "{{ usage_location }}"
      mail: "{{ mail }}"
