---
- hosts: localhost
  vars:
    email: "user@server.com"
    tenant: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
  tasks:
  - name: Using user_principal_name
    azure.azcollection.azure_rm_aduser_info:
     user_principal_name: "{{ email }}"
     tenant: "{{ tenant }}"
    register: founduser

  - name: Print user details
    ansible.builtin.debug:
      var: founduser
